[2022-10-30 14:04:13 +0800] [11070] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:04:13 +0800] [11070] [INFO] Listening at: http://0.0.0.0:8091 (11070)
[2022-10-30 14:04:13 +0800] [11070] [INFO] Using worker: gevent
[2022-10-30 14:04:13 +0800] [11071] [INFO] Booting worker with pid: 11071
Traceback (most recent call last):
  File "/root/flaskMusic/controllers/fun1.py", line 87, in getOrderSong
    result = json.loads(result)
  File "/usr/lib64/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
music result <Music 192>
music result <Music 131>
Traceback (most recent call last):
  File "/root/flaskMusic/controllers/fun1.py", line 87, in getOrderSong
    result = json.loads(result)
  File "/usr/lib64/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
music result <Music 100>
[2022-10-30 14:04:58 +0800] [11071] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/flaskMusic/controllers/fun1.py", line 13, in login
    phone = request.form['phone']
  File "/usr/local/lib/python3.6/site-packages/werkzeug/datastructures.py", line 377, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'phone'
[2022-10-30 14:05:34 +0800] [11070] [WARNING] Worker with pid 11071 was terminated due to signal 9
[2022-10-30 14:05:34 +0800] [11078] [INFO] Booting worker with pid: 11078
[2022-10-30 14:06:21 +0800] [11086] [INFO] Starting gunicorn 20.1.0

Error: Already running on PID 11070 (or pid file '/root/flaskMusic/logs/gunicorn.pid' is stale)

[2022-10-30 14:07:04 +0800] [11078] [INFO] Parent changed, shutting down: <Worker 11078>
[2022-10-30 14:07:04 +0800] [11078] [INFO] Worker exiting (pid: 11078)
[2022-10-30 14:07:07 +0800] [11094] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:07:07 +0800] [11094] [INFO] Listening at: http://0.0.0.0:8091 (11094)
[2022-10-30 14:07:07 +0800] [11094] [INFO] Using worker: gevent
[2022-10-30 14:07:07 +0800] [11095] [INFO] Booting worker with pid: 11095
[2022-10-30 14:07:15 +0800] [11095] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/flaskMusic/controllers/fun1.py", line 17, in login
    access_token = generate_access_token(user_name=name)
NameError: name 'name' is not defined
[2022-10-30 14:08:16 +0800] [11095] [INFO] Parent changed, shutting down: <Worker 11095>
[2022-10-30 14:08:16 +0800] [11095] [INFO] Worker exiting (pid: 11095)
[2022-10-30 14:08:20 +0800] [11106] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:08:20 +0800] [11106] [INFO] Listening at: http://0.0.0.0:8091 (11106)
[2022-10-30 14:08:20 +0800] [11106] [INFO] Using worker: gevent
[2022-10-30 14:08:20 +0800] [11107] [INFO] Booting worker with pid: 11107
[2022-10-30 14:08:23 +0800] [11107] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/flaskMusic/controllers/fun1.py", line 19, in login
    data = {"access_token": access_token.decode("utf-8"),
AttributeError: 'str' object has no attribute 'decode'
[2022-10-30 14:08:25 +0800] [11107] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/flaskMusic/controllers/fun1.py", line 19, in login
    data = {"access_token": access_token.decode("utf-8"),
AttributeError: 'str' object has no attribute 'decode'
[2022-10-30 14:14:58 +0800] [11107] [INFO] Parent changed, shutting down: <Worker 11107>
[2022-10-30 14:14:58 +0800] [11107] [INFO] Worker exiting (pid: 11107)
[2022-10-30 14:15:01 +0800] [11138] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:15:01 +0800] [11138] [INFO] Listening at: http://0.0.0.0:8091 (11138)
[2022-10-30 14:15:01 +0800] [11138] [INFO] Using worker: gevent
[2022-10-30 14:15:01 +0800] [11139] [INFO] Booting worker with pid: 11139
[2022-10-30 14:15:01 +0800] [11139] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/flaskMusic/app.py", line 3, in <module>
    from routers import b1
  File "/root/flaskMusic/routers/__init__.py", line 2, in <module>
    from controllers.fun1 import login, register, sql_query, get_song, get_song_amount, getSongByLbl, uploadMusic, orderSongById, getOrderSong
  File "/root/flaskMusic/controllers/fun1.py", line 19
    print(access_token, refresh_token)
                                     ^
TabError: inconsistent use of tabs and spaces in indentation
[2022-10-30 14:15:01 +0800] [11139] [INFO] Worker exiting (pid: 11139)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-10-30T06:15:01Z <Greenlet at 0x7f6621f8c648: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f66231eb6d8>>(17, None)> failed with HaltServer

[2022-10-30 14:15:31 +0800] [11138] [CRITICAL] WORKER TIMEOUT (pid:11139)
[2022-10-30 14:15:31 +0800] [11142] [INFO] Booting worker with pid: 11142
[2022-10-30 14:15:31 +0800] [11142] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/flaskMusic/app.py", line 3, in <module>
    from routers import b1
  File "/root/flaskMusic/routers/__init__.py", line 2, in <module>
    from controllers.fun1 import login, register, sql_query, get_song, get_song_amount, getSongByLbl, uploadMusic, orderSongById, getOrderSong
  File "/root/flaskMusic/controllers/fun1.py", line 19
    print(access_token, refresh_token)
                                     ^
TabError: inconsistent use of tabs and spaces in indentation
[2022-10-30 14:15:31 +0800] [11142] [INFO] Worker exiting (pid: 11142)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-10-30T06:15:31Z <Greenlet at 0x7f6621f8c648: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f66231eb6d8>>(17, None)> failed with HaltServer

[2022-10-30 14:16:01 +0800] [11138] [CRITICAL] WORKER TIMEOUT (pid:11142)
[2022-10-30 14:16:01 +0800] [11145] [INFO] Booting worker with pid: 11145
[2022-10-30 14:16:01 +0800] [11145] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/flaskMusic/app.py", line 3, in <module>
    from routers import b1
  File "/root/flaskMusic/routers/__init__.py", line 2, in <module>
    from controllers.fun1 import login, register, sql_query, get_song, get_song_amount, getSongByLbl, uploadMusic, orderSongById, getOrderSong
  File "/root/flaskMusic/controllers/fun1.py", line 19
    print(access_token, refresh_token)
                                     ^
TabError: inconsistent use of tabs and spaces in indentation
[2022-10-30 14:16:01 +0800] [11145] [INFO] Worker exiting (pid: 11145)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-10-30T06:16:01Z <Greenlet at 0x7f6621f8c648: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f66231eb6d8>>(17, None)> failed with HaltServer

[2022-10-30 14:16:20 +0800] [11152] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:16:20 +0800] [11152] [INFO] Listening at: http://0.0.0.0:8091 (11152)
[2022-10-30 14:16:20 +0800] [11152] [INFO] Using worker: gevent
[2022-10-30 14:16:20 +0800] [11153] [INFO] Booting worker with pid: 11153
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjcxMTc3ODMsImZsYWciOjAsImlhdCI6MTY2NzExMDU4MywiaXNzIjoiam9leSIsInVzZXJfbmFtZSI6ImFkbWluIn0.7s1FffOBL6_SOj5mquwIbKvGZCtX76PNN9llgJfzoz8 eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Njk3MDI1ODMsImZsYWciOjEsImlhdCI6MTY2NzExMDU4MywiaXNzIjoiam9leSIsInVzZXJfbmFtZSI6ImFkbWluIn0.ECJbKeNkoipfd5MtPbtWvEFJFL5NNsgzuvnMnFnhSoY
[2022-10-30 14:16:41 +0800] [11153] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 127, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/flaskMusic/controllers/fun1.py", line 13, in login
    phone = request.form['phone']
  File "/usr/local/lib/python3.6/site-packages/werkzeug/datastructures.py", line 377, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'phone'
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjcxMTc4NzIsImZsYWciOjAsImlhdCI6MTY2NzExMDY3MiwiaXNzIjoiam9leSIsInVzZXJfbmFtZSI6ImFkbWluIn0.uH4ARO-SiAlPCHSX3-WCVS3IdzoW1W-MkPS0VfkMeiM eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Njk3MDI2NzIsImZsYWciOjEsImlhdCI6MTY2NzExMDY3MiwiaXNzIjoiam9leSIsInVzZXJfbmFtZSI6ImFkbWluIn0.cb3vpcEqckDhPFJmoJ2DYimbPfYdjoK362ICYST6vDY
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjcxMTc5OTcsImZsYWciOjAsImlhdCI6MTY2NzExMDc5NywiaXNzIjoiam9leSIsInVzZXJfbmFtZSI6ImFkbWluIn0.RDw-FbOjsmXZppv7Tevul5IoY5aNCQgfG0Le6wymGq4 eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Njk3MDI3OTcsImZsYWciOjEsImlhdCI6MTY2NzExMDc5NywiaXNzIjoiam9leSIsInVzZXJfbmFtZSI6ImFkbWluIn0.CQb5tQXiH8gb3cdM7aIWOnlkRUZEy7JV4Z7BRsQmaus
[2022-10-30 14:22:34 +0800] [11153] [INFO] Parent changed, shutting down: <Worker 11153>
[2022-10-30 14:22:34 +0800] [11153] [INFO] Worker exiting (pid: 11153)
[2022-10-30 14:23:30 +0800] [11168] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:23:30 +0800] [11168] [INFO] Listening at: http://0.0.0.0:8091 (11168)
[2022-10-30 14:23:30 +0800] [11168] [INFO] Using worker: gevent
[2022-10-30 14:23:30 +0800] [11169] [INFO] Booting worker with pid: 11169
music result <Music 132>
Traceback (most recent call last):
  File "/root/flaskMusic/controllers/fun1.py", line 88, in getOrderSong
    result = json.loads(result)
  File "/usr/lib64/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
music result <Music 41>
[2022-10-30 14:27:45 +0800] [11169] [INFO] Parent changed, shutting down: <Worker 11169>
[2022-10-30 14:27:45 +0800] [11169] [INFO] Worker exiting (pid: 11169)
[2022-10-30 14:27:51 +0800] [11181] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:27:51 +0800] [11181] [INFO] Listening at: http://0.0.0.0:8091 (11181)
[2022-10-30 14:27:51 +0800] [11181] [INFO] Using worker: gevent
[2022-10-30 14:27:51 +0800] [11182] [INFO] Booting worker with pid: 11182
[2022-10-30 14:28:52 +0800] [11182] [INFO] Parent changed, shutting down: <Worker 11182>
[2022-10-30 14:28:52 +0800] [11182] [INFO] Worker exiting (pid: 11182)
[2022-10-30 14:28:55 +0800] [11189] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:28:55 +0800] [11189] [INFO] Listening at: http://0.0.0.0:8091 (11189)
[2022-10-30 14:28:55 +0800] [11189] [INFO] Using worker: gevent
[2022-10-30 14:28:55 +0800] [11190] [INFO] Booting worker with pid: 11190
[2022-10-30 14:28:56 +0800] [11190] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/flaskMusic/app.py", line 3, in <module>
    from routers import b1
  File "/root/flaskMusic/routers/__init__.py", line 2, in <module>
    from controllers.fun1 import login, register, sql_query, get_song, get_song_amount, getSongByLbl, uploadMusic, orderSongById, getOrderSong
  File "/root/flaskMusic/controllers/fun1.py", line 7, in <module>
    from utils.jwt_util import generate_access_token, generate_refresh_token, decode_auth_token, identify, login_required
  File "/root/flaskMusic/utils/jwt_util.py", line 76
    print(payload)
                 ^
TabError: inconsistent use of tabs and spaces in indentation
[2022-10-30 14:28:56 +0800] [11190] [INFO] Worker exiting (pid: 11190)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-10-30T06:28:56Z <Greenlet at 0x7fb3c1f7e648: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fb3c316f908>>(17, None)> failed with HaltServer

[2022-10-30 14:29:25 +0800] [11189] [CRITICAL] WORKER TIMEOUT (pid:11190)
[2022-10-30 14:29:25 +0800] [11193] [INFO] Booting worker with pid: 11193
[2022-10-30 14:29:26 +0800] [11193] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/flaskMusic/app.py", line 3, in <module>
    from routers import b1
  File "/root/flaskMusic/routers/__init__.py", line 2, in <module>
    from controllers.fun1 import login, register, sql_query, get_song, get_song_amount, getSongByLbl, uploadMusic, orderSongById, getOrderSong
  File "/root/flaskMusic/controllers/fun1.py", line 7, in <module>
    from utils.jwt_util import generate_access_token, generate_refresh_token, decode_auth_token, identify, login_required
  File "/root/flaskMusic/utils/jwt_util.py", line 76
    print(payload)
                 ^
TabError: inconsistent use of tabs and spaces in indentation
[2022-10-30 14:29:26 +0800] [11193] [INFO] Worker exiting (pid: 11193)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-10-30T06:29:26Z <Greenlet at 0x7fb3c1f7e648: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7fb3c316f908>>(17, None)> failed with HaltServer

[2022-10-30 14:29:55 +0800] [11189] [CRITICAL] WORKER TIMEOUT (pid:11193)
[2022-10-30 14:29:55 +0800] [11196] [INFO] Booting worker with pid: 11196

[2022-10-30 14:31:24 +0800] [11196] [INFO] Parent changed, shutting down: <Worker 11196>
[2022-10-30 14:31:24 +0800] [11196] [INFO] Worker exiting (pid: 11196)
[2022-10-30 14:31:28 +0800] [11208] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:31:28 +0800] [11208] [INFO] Listening at: http://0.0.0.0:8091 (11208)
[2022-10-30 14:31:28 +0800] [11208] [INFO] Using worker: gevent
[2022-10-30 14:31:28 +0800] [11209] [INFO] Booting worker with pid: 11209


[2022-10-30 14:32:21 +0800] [11209] [INFO] Parent changed, shutting down: <Worker 11209>
[2022-10-30 14:32:21 +0800] [11209] [INFO] Worker exiting (pid: 11209)
[2022-10-30 14:32:25 +0800] [11218] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:32:25 +0800] [11218] [INFO] Listening at: http://0.0.0.0:8091 (11218)
[2022-10-30 14:32:25 +0800] [11218] [INFO] Using worker: gevent
[2022-10-30 14:32:25 +0800] [11219] [INFO] Booting worker with pid: 11219
payload:  
payload:  
[2022-10-30 14:34:08 +0800] [11219] [INFO] Parent changed, shutting down: <Worker 11219>
[2022-10-30 14:34:08 +0800] [11219] [INFO] Worker exiting (pid: 11219)
[2022-10-30 14:34:11 +0800] [11229] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:34:11 +0800] [11229] [INFO] Listening at: http://0.0.0.0:8091 (11229)
[2022-10-30 14:34:11 +0800] [11229] [INFO] Using worker: gevent
[2022-10-30 14:34:11 +0800] [11230] [INFO] Booting worker with pid: 11230
[2022-10-30 14:34:12 +0800] [11230] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/flaskMusic/app.py", line 3, in <module>
    from routers import b1
  File "/root/flaskMusic/routers/__init__.py", line 2, in <module>
    from controllers.fun1 import login, register, sql_query, get_song, get_song_amount, getSongByLbl, uploadMusic, orderSongById, getOrderSong
  File "/root/flaskMusic/controllers/fun1.py", line 7, in <module>
    from utils.jwt_util import generate_access_token, generate_refresh_token, decode_auth_token, identify, login_required
  File "/root/flaskMusic/utils/jwt_util.py", line 64
    print(f'decode payload: {payload}')
                                      ^
TabError: inconsistent use of tabs and spaces in indentation
[2022-10-30 14:34:12 +0800] [11230] [INFO] Worker exiting (pid: 11230)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-10-30T06:34:12Z <Greenlet at 0x7f5204741648: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f52059a06a0>>(17, None)> failed with HaltServer

[2022-10-30 14:34:41 +0800] [11229] [CRITICAL] WORKER TIMEOUT (pid:11230)
[2022-10-30 14:34:41 +0800] [11232] [INFO] Booting worker with pid: 11232
[2022-10-30 14:34:42 +0800] [11232] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/flaskMusic/app.py", line 3, in <module>
    from routers import b1
  File "/root/flaskMusic/routers/__init__.py", line 2, in <module>
    from controllers.fun1 import login, register, sql_query, get_song, get_song_amount, getSongByLbl, uploadMusic, orderSongById, getOrderSong
  File "/root/flaskMusic/controllers/fun1.py", line 7, in <module>
    from utils.jwt_util import generate_access_token, generate_refresh_token, decode_auth_token, identify, login_required
  File "/root/flaskMusic/utils/jwt_util.py", line 64
    print(f'decode payload: {payload}')
                                      ^
TabError: inconsistent use of tabs and spaces in indentation
[2022-10-30 14:34:42 +0800] [11232] [INFO] Worker exiting (pid: 11232)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-10-30T06:34:42Z <Greenlet at 0x7f5204741648: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f52059a06a0>>(17, None)> failed with HaltServer

[2022-10-30 14:35:11 +0800] [11229] [CRITICAL] WORKER TIMEOUT (pid:11232)
[2022-10-30 14:35:11 +0800] [11236] [INFO] Booting worker with pid: 11236
[2022-10-30 14:35:12 +0800] [11236] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/flaskMusic/app.py", line 3, in <module>
    from routers import b1
  File "/root/flaskMusic/routers/__init__.py", line 2, in <module>
    from controllers.fun1 import login, register, sql_query, get_song, get_song_amount, getSongByLbl, uploadMusic, orderSongById, getOrderSong
  File "/root/flaskMusic/controllers/fun1.py", line 7, in <module>
    from utils.jwt_util import generate_access_token, generate_refresh_token, decode_auth_token, identify, login_required
  File "/root/flaskMusic/utils/jwt_util.py", line 64
    print(f'decode payload: {payload}')
                                      ^
TabError: inconsistent use of tabs and spaces in indentation
[2022-10-30 14:35:12 +0800] [11236] [INFO] Worker exiting (pid: 11236)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-10-30T06:35:12Z <Greenlet at 0x7f5204741648: <bound method Arbiter.handle_chld of <gunicorn.arbiter.Arbiter object at 0x7f52059a06a0>>(17, None)> failed with HaltServer

[2022-10-30 14:35:24 +0800] [11243] [INFO] Starting gunicorn 20.1.0

Error: Already running on PID 11229 (or pid file '/root/flaskMusic/logs/gunicorn.pid' is stale)

[2022-10-30 14:35:43 +0800] [11249] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:35:43 +0800] [11249] [INFO] Listening at: http://0.0.0.0:8091 (11249)
[2022-10-30 14:35:43 +0800] [11249] [INFO] Using worker: gevent
[2022-10-30 14:35:43 +0800] [11250] [INFO] Booting worker with pid: 11250
[2022-10-30 14:38:44 +0800] [11250] [INFO] Parent changed, shutting down: <Worker 11250>
[2022-10-30 14:38:44 +0800] [11250] [INFO] Worker exiting (pid: 11250)
[2022-10-30 14:38:47 +0800] [11261] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:38:47 +0800] [11261] [INFO] Listening at: http://0.0.0.0:8091 (11261)
[2022-10-30 14:38:47 +0800] [11261] [INFO] Using worker: gevent
[2022-10-30 14:38:47 +0800] [11262] [INFO] Booting worker with pid: 11262
decode token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Njk3MDM3NDYsImZsYWciOjEsImlhdCI6MTY2NzExMTc0NiwiaXNzIjoiam9leSIsInVzZXJfbmFtZSI6ImFkbWluIn0.-tYLa10qmsBRGbA56DWA_aH_Ynhda_tf8EwCTM6RTqQ
[2022-10-30 14:40:55 +0800] [11262] [INFO] Parent changed, shutting down: <Worker 11262>
[2022-10-30 14:40:55 +0800] [11262] [INFO] Worker exiting (pid: 11262)
[2022-10-30 14:41:10 +0800] [11279] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:41:10 +0800] [11279] [INFO] Listening at: http://0.0.0.0:8091 (11279)
[2022-10-30 14:41:10 +0800] [11279] [INFO] Using worker: gevent
[2022-10-30 14:41:10 +0800] [11280] [INFO] Booting worker with pid: 11280
decode token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Njk3MDM3NDYsImZsYWciOjEsImlhdCI6MTY2NzExMTc0NiwiaXNzIjoiam9leSIsInVzZXJfbmFtZSI6ImFkbWluIn0.-tYLa10qmsBRGbA56DWA_aH_Ynhda_tf8EwCTM6RTqQ
Traceback (most recent call last):
  File "/root/flaskMusic/utils/jwt_util.py", line 65, in decode_auth_token
    payload = jwt.decode(token, key=key)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 97, in decode_complete
    'It is required that you pass in a value for the "algorithms" argument when calling decode().'
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
[2022-10-30 14:42:40 +0800] [11280] [INFO] Parent changed, shutting down: <Worker 11280>
[2022-10-30 14:42:40 +0800] [11280] [INFO] Worker exiting (pid: 11280)
[2022-10-30 14:42:42 +0800] [11288] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:42:42 +0800] [11288] [INFO] Listening at: http://0.0.0.0:8091 (11288)
[2022-10-30 14:42:42 +0800] [11288] [INFO] Using worker: gevent
[2022-10-30 14:42:42 +0800] [11289] [INFO] Booting worker with pid: 11289
Traceback (most recent call last):
  File "/root/flaskMusic/utils/jwt_util.py", line 64, in decode_auth_token
    payload = jwt.decode(token, key=key, algorithm=algorithm)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 97, in decode_complete
    'It is required that you pass in a value for the "algorithms" argument when calling decode().'
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
[2022-10-30 14:45:25 +0800] [11289] [INFO] Parent changed, shutting down: <Worker 11289>
[2022-10-30 14:45:25 +0800] [11289] [INFO] Worker exiting (pid: 11289)
[2022-10-30 14:45:35 +0800] [11311] [INFO] Starting gunicorn 20.1.0
[2022-10-30 14:45:35 +0800] [11311] [INFO] Listening at: http://0.0.0.0:8091 (11311)
[2022-10-30 14:45:35 +0800] [11311] [INFO] Using worker: gevent
[2022-10-30 14:45:35 +0800] [11312] [INFO] Booting worker with pid: 11312
Traceback (most recent call last):
  File "/root/flaskMusic/controllers/fun1.py", line 88, in getOrderSong
    result = json.loads(result)
  File "/usr/lib64/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
music result <Music 163>
music result <Music 194>
music result <Music 426>
music result <Music 426>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 220, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/flaskMusic/utils/jwt_util.py", line 64, in decode_auth_token
    payload = jwt.decode(token, key=key, algorithms=algorithm)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 105, in decode_complete
    **kwargs,
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 171, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 223, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
music result <Music 426>
music result <Music 412>
music result <Music 426>
music result <Music 420>
[2022-10-30 15:05:06 +0800] [11312] [INFO] Parent changed, shutting down: <Worker 11312>
[2022-10-30 15:05:06 +0800] [11312] [INFO] Worker exiting (pid: 11312)
[2022-10-30 15:05:09 +0800] [11349] [INFO] Starting gunicorn 20.1.0
[2022-10-30 15:05:09 +0800] [11349] [INFO] Listening at: http://0.0.0.0:8091 (11349)
[2022-10-30 15:05:09 +0800] [11349] [INFO] Using worker: gevent
[2022-10-30 15:05:09 +0800] [11350] [INFO] Booting worker with pid: 11350
music result <Music 426>
music result <Music 421>
music result <Music 421>
[2022-10-30 15:12:25 +0800] [11350] [INFO] Parent changed, shutting down: <Worker 11350>
[2022-10-30 15:12:25 +0800] [11350] [INFO] Worker exiting (pid: 11350)
[2022-10-30 15:12:26 +0800] [11367] [INFO] Starting gunicorn 20.1.0
[2022-10-30 15:12:26 +0800] [11367] [INFO] Listening at: http://0.0.0.0:8091 (11367)
[2022-10-30 15:12:26 +0800] [11367] [INFO] Using worker: gevent
[2022-10-30 15:12:26 +0800] [11368] [INFO] Booting worker with pid: 11368
music result <Music 421>
music result <Music 424>
music result <Music 138>
music result <Music 253>
music result <Music 80>
music result <Music 369>
music result <Music 158>
music result <Music 124>
music result <Music 316>
music result <Music 346>
music result <Music 185>
music result <Music 236>
music result <Music 372>
music result <Music 371>
music result <Music 182>
music result <Music 74>
music result <Music 313>
music result <Music 281>
music result <Music 413>
music result <Music 405>
music result <Music 418>
music result <Music 404>
music result <Music 424>
music result <Music 294>
music result <Music 69>
music result <Music 108>
music result <Music 167>
music result <Music 210>
file name: 0f91e113b2b822fe2d62cfd1ae8750b6.mp3
save path: /root/music/music/teenager_group/0f91e113b2b822fe2d62cfd1ae8750b6.mp3
music result <Music 276>
music result <Music 434>
file name: fb0e3ac980b619528f505088dd3c6506.mp3
save path: /root/music/music/teenager_group/fb0e3ac980b619528f505088dd3c6506.mp3
music result <Music 435>
music result <Music 99>
music result <Music 319>
music result <Music 279>
music result <Music 381>
music result <Music 21>
music result <Music 405>
music result <Music 104>
music result <Music 353>
music result <Music 206>
music result <Music 187>
music result <Music 33>
music result <Music 76>
music result <Music 357>
music result <Music 38>
music result <Music 376>
music result <Music 321>
music result <Music 290>
music result <Music 407>
music result <Music 347>
music result <Music 177>
music result <Music 336>
music result <Music 9>
music result <Music 334>
music result <Music 144>
music result <Music 415>
music result <Music 140>
music result <Music 294>
music result <Music 427>
music result <Music 402>
music result <Music 284>
music result <Music 38>
music result <Music 68>
music result <Music 241>
music result <Music 268>
music result <Music 177>
music result <Music 197>
music result <Music 294>
music result <Music 382>
music result <Music 322>
music result <Music 420>
music result <Music 228>
music result <Music 284>
music result <Music 435>
music result <Music 420>
music result <Music 416>
file name: 4c5761f6158d9c194aaa33ce9941f189.mp3
save path: /root/music/music/teenager_group/4c5761f6158d9c194aaa33ce9941f189.mp3
music result <Music 104>
music result <Music 13>
music result <Music 100>
music result <Music 56>
music result <Music 278>
music result <Music 236>
music result <Music 430>
music result <Music 29>
music result <Music 410>
music result <Music 367>
music result <Music 421>
music result <Music 403>
music result <Music 60>
music result <Music 59>
music result <Music 322>
music result <Music 271>
music result <Music 125>
music result <Music 241>
music result <Music 277>
music result <Music 421>
music result <Music 107>
music result <Music 204>
music result <Music 403>
music result <Music 272>
music result <Music 188>
music result <Music 297>
music result <Music 304>
music result <Music 376>
music result <Music 431>
music result <Music 353>
music result <Music 296>
music result <Music 197>
music result <Music 217>
music result <Music 164>
music result <Music 398>
music result <Music 226>
music result <Music 260>
music result <Music 71>
music result <Music 362>
music result <Music 230>
music result <Music 239>
music result <Music 310>
music result <Music 338>
music result <Music 22>
music result <Music 402>
music result <Music 370>
music result <Music 268>
music result <Music 118>
music result <Music 129>
music result <Music 278>
music result <Music 64>
music result <Music 273>
music result <Music 221>
music result <Music 232>
music result <Music 379>
[2022-10-30 18:04:28 +0800] [11368] [INFO] Parent changed, shutting down: <Worker 11368>
[2022-10-30 18:04:28 +0800] [11368] [INFO] Worker exiting (pid: 11368)
[2022-10-30 18:13:24 +0800] [11831] [INFO] Starting gunicorn 20.1.0
[2022-10-30 18:13:24 +0800] [11831] [INFO] Listening at: http://0.0.0.0:8091 (11831)
[2022-10-30 18:13:24 +0800] [11831] [INFO] Using worker: gevent
[2022-10-30 18:13:24 +0800] [11832] [INFO] Booting worker with pid: 11832
music result <Music 209>
music result <Music 323>
Traceback (most recent call last):
  File "/root/flaskMusic/utils/jwt_util.py", line 63, in decode_auth_token
    payload = jwt.decode(token, key=key, algorithms=algorithm)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 105, in decode_complete
    **kwargs,
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 182, in decode_complete
    self._verify_signature(signing_input, header, signature, key, algorithms)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 269, in _verify_signature
    raise InvalidSignatureError("Signature verification failed")
jwt.exceptions.InvalidSignatureError: Signature verification failed
music result <Music 323>
music result <Music 209>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 220, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/flaskMusic/utils/jwt_util.py", line 63, in decode_auth_token
    payload = jwt.decode(token, key=key, algorithms=algorithm)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 105, in decode_complete
    **kwargs,
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 171, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 223, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
[2022-10-30 18:20:22 +0800] [11832] [INFO] Parent changed, shutting down: <Worker 11832>
[2022-10-30 18:20:22 +0800] [11832] [INFO] Worker exiting (pid: 11832)
[2022-10-30 18:20:27 +0800] [11848] [INFO] Starting gunicorn 20.1.0
[2022-10-30 18:20:27 +0800] [11848] [INFO] Listening at: http://0.0.0.0:8091 (11848)
[2022-10-30 18:20:27 +0800] [11848] [INFO] Using worker: gevent
[2022-10-30 18:20:28 +0800] [11849] [INFO] Booting worker with pid: 11849
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 220, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/flaskMusic/utils/jwt_util.py", line 63, in decode_auth_token
    payload = jwt.decode(token, key=key, algorithms=algorithm)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 105, in decode_complete
    **kwargs,
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 171, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 223, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 220, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/flaskMusic/utils/jwt_util.py", line 63, in decode_auth_token
    payload = jwt.decode(token, key=key, algorithms=algorithm)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 105, in decode_complete
    **kwargs,
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 171, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 223, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 220, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/flaskMusic/utils/jwt_util.py", line 63, in decode_auth_token
    payload = jwt.decode(token, key=key, algorithms=algorithm)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 105, in decode_complete
    **kwargs,
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 171, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 223, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 220, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/flaskMusic/utils/jwt_util.py", line 63, in decode_auth_token
    payload = jwt.decode(token, key=key, algorithms=algorithm)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 105, in decode_complete
    **kwargs,
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 171, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 223, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
music result <Music 323>
music result <Music 386>
music result <Music 27>
music result <Music 113>
music result <Music 427>
music result <Music 184>
music result <Music 425>
music result <Music 413>
music result <Music 418>
music result <Music 46>
music result <Music 315>
music result <Music 185>
music result <Music 323>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 220, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/flaskMusic/utils/jwt_util.py", line 63, in decode_auth_token
    payload = jwt.decode(token, key=key, algorithms=algorithm)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 129, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 105, in decode_complete
    **kwargs,
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 171, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 223, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
music result <Music 367>
music result <Music 26>
music result <Music 59>
music result <Music 280>
music result <Music 357>
music result <Music 20>
music result <Music 215>
music result <Music 420>
music result <Music 257>
music result <Music 354>
music result <Music 420>
